package livetemplate;

import java.util.Random;

public final class CommentGenerator {

    private CommentGenerator() { }

    private static final String[] COMMENTS = {
            "For the brave souls who get this far: You are the chosen ones, the valiant knights of programming who toil away, without rest, fixing our most awful code. To you, true saviors, kings of men, I say this: never gonna give you up, never gonna let you down, never gonna run around and desert you. Never gonna make you cry, never gonna say goodbye. Never gonna tell a lie and hurt you.",
            "When I wrote this, only God and I understood what I was doing Now, God only knows",
            "Autogenerated, do not edit. All changes will be undone.",
            "sometimes I believe compiler ignores all my comments",
            "stop(); // Hammertime!",
            "I dedicate all this code, all my work, to my wife, Darlene, who will have to support me and our three children and the dog once it gets released into the public.",
            "Drunk, fix later",
            "Magic. Do not touch.",
            "I'm sorry.",
            "This is O(scary), but seems quick enough in practice.",
            "If this comment is removed the program will blow up.",
            "I am not sure if we need this, but too scared to delete.",
            "Please work.",
            "Dear future me. Please forgive me. I can't even begin to express how sorry I am.",
            "You are not meant to understand this.",
            "I have to find a better job.",
            "If dolphins are so smart, how come they live in Igloos?",
            "This comment included for the benefit of anyone grepping for swearwords: shit.",
            "If you don't understand this code, you should be flipping burgers instead.",
            "Ah ah ah! You'll never understand why this one works.",
            "Mr. Compiler, please do not read this.",
            "Remove this if you wanna be fired.",
            "This code makes baby Jesus very sad!",
            "Jesus told me to skip to the end of the message here.",
            "This is crap code but it's 3 a.m. and I need to get this working.",
            "Houston, we have a problem.",
            "This should fix something that should never happen.",
            "I don't understand how the following bit works, but it worked in the program I stole it from.\n",
            "Sun, you just can't beat me, you just can't.  Stop trying, give up.  I'm serious, I am going to kick the living shit out of you, game over, lights out.",
            "The following code is commented out (a load of commented out code followed)",
            "This was clearly written under duress.",
            "Hard to explain.",
            "Abandon all hope you who needs to debug this.",
            "Don't ask about these magic sequences.  I took them straight from gas-1.36 which took them from the a.out man page.",
            "The world is a happy place.",
            "This code worked before, but my cat decided to take a trip across my keyboard...",
            "When I wrote this, only God and I understood what I was doing. Now, God only knows",
            "I'm not paid for this...",
    };

    public static String generateRandom() {
//        long range = (long)COMMENTS.length;
//        long fraction = (long)(range * new Random().nextDouble());
//        return COMMENTS[(int) (fraction + 0)];
        return COMMENTS[3];
    }

    public static String getForgiveness() {
        return COMMENTS[13];
    }
}
